### ISSUE TITLE
`superseded_by` fields with `null` values causing multiple versions of same products to appear in API searches

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry-sweepers#112] opened 2024-03-28 17:01 UTC
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

https://pds.nasa.gov/api/search/1/products?q=(lid%20eq%20%22urn:nasa:pds:lro_lola_edr:data_raw%22) 2 records appear.

### 🕵️ Expected behavior

I expected 1 product to be returned

### 📜 To Reproduce

https://pds.nasa.gov/api/search/1/products?q=(lid%20eq%20%22urn:nasa:pds:lro_lola_edr:data_raw%22)

```json
"summary": {
  "q": "(lid eq \"urn:nasa:pds:lro_lola_edr:data_raw\")",
  "hits": 2,
  "took": 90,
  "search_after": [],
  "limit": 100,
  "sort": [],
  "properties": [
  ...
  "lidvid": [
    "urn:nasa:pds:lro_lola_edr:data_raw::4.0"
  ],
  ...
  "ops:Provenance.ops:superseded_by": [
    "null"
  ],
  ..
  "lidvid": [
    "urn:nasa:pds:lro_lola_edr:data_raw::5.0"
  ],
  ...
```

### 🖥 Environment Info

Chrome

### 📚 Version of Software Used

Latest

**Comment by alexdunnjpl** [comment] 2024-04-18 17:58
@jordanpadams I'll investigate shortly, but is it plausible that the two documents in question exist on different nodes and that's why they lack correct provenance history?

**Comment by jordanpadams** [comment] 2024-04-18 18:03
@alexdunnjpl hmmm. that would be interesting. they both say GEO, but I wonder if we loaded that data as a test case into the EN registry?

**Comment by alexdunnjpl** [comment] 2024-04-18 18:32
I'll dig into that now.  If it ends up being the case that they're in two nodes, 

- is this an expected case which the API must handle?
- is the expected behaviour in this case that the higher VID should prevail?

**Comment by alexdunnjpl** [comment] 2024-04-18 19:03
@jordanpadams if I'm interpreting the swagger docs correctly, I don't think the request/expectation in the original ticket is even valid.
 
 latest/all subroutes are only defined for `/products/{identifier}/{all | latest}`.  In that case, it's reasonable to expect that no latest/all specification yields only the latest product.
 
But why would there be any expectation that `/products/?q=somequery` would only return the latest version of the LIDs of the full set of products resulting from that query?

1.  Intuitively, the result of a query should be that you get what you ask for
2. Even if 1) isn't persuasive, there's no way to specify `/products/all?q=somequery` because `all` would be parsed as an identifier.  And it seems implausible that there should be no way to use a custom query to get all the products you want.

**Comment by jordanpadams** [comment] 2024-04-18 19:32
> But why would there be any expectation that /products/?q=somequery would only return the latest version of the LIDs of the full set of products resulting from that query?

It is a requirement of the system that only the latest versions of products be returned, by default, unless otherwise stated.

https://github.com/NASA-PDS/registry-api/issues/428
https://github.com/NASA-PDS/registry-api/issues/426

Moving the rest of the discussion to NASA-PDS/registry-api#428 since I think it is more deservedly had there.

**Comment by alexdunnjpl** [comment] 2024-04-18 19:36
Task definition is v5 ARN`arn:aws:ecs:us-west-2:445837347542:task-definition/pds-geo-prod-registry-sweepers-task:5` despite latest version of that task being v9 `arn:aws:ecs:us-west-2:445837347542:task-definition/pds-geo-prod-registry-sweepers-task:9`

This may explain #123 as well, if it is also lagging behind in versions.

@sjoshi-jpl is there any reason why the schedulers shouldn't be targeting the latest version of the relevant task definition?

**Comment by alexdunnjpl** [comment] 2024-05-16 21:04
@sjoshi-jpl re-pinging for the question above.  "This doesn't matter because we're moving to MCP" is an acceptable answer, too.

**Comment by tloubrieu-jpl** [comment] 2024-05-16 22:07
If we use the latest version of the reistry-sweeper this should not happend again.

`superseeded_by: null` should be only for the latest product.

**Closed** 2024-05-16 22:07 UTC
Labels: B15.0, bug, s.high, sprint-backlog

**Comment by alexdunnjpl** [comment] 2024-05-17 00:20
N.B. the root cause here is that sweepers has not run successfully since the latest product was ingested (probably due to the timeout issue).

It's not a bug, but may resurface.
